spring.application.name=microservice
server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/techstore
spring.datasource.username=postgres
spring.datasource.password=Nykolas2111
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.sql.init.mode=always

security.jwt.secret=TechStoreJwtSecretKeyForHs256Signing_ChangeInProd2026
security.jwt.expiration-seconds=3600
